
###
POST http://localhost:8080/kunden
Content-Type: application/json

{
  "id": 1,
  "name": "Klaus",
  "email": "du@htw.de",
  "telefonnummer": "123456789",
  "allergien": "keine"

  }

###
POST http://localhost:8080/reservierungen
Content-Type: application/json

{
  "kundenId": 1,
    "tischSlotId":1
}

###
POST http://localhost:8080/tische
Content-Type: application/json

{
  "id": 20,

  "anzahlPlaetze": 4

}

###
GET http://localhost:8080/kunden/1
Content-Type: application/json




###
DELETE http://localhost:8080/tische/26
Content-Type: application/json


###
GET http://localhost:8080/reservierungen
Content-Type: application/json



###
GET http://localhost:8080/reservierungen/1
Content-Type: application/json

###
GET http://localhost:8080/reservierungen
Content-Type: application/json

