###
POST http://localhost:8080/kunden
Content-Type: application/json

{
  "id": 1,
  "name": "Klaus",
  "email": "du@htw.de",
  "telefonnummer": "123456789",
  "allergien": "keine"

  }
###
POST http://localhost:8080/reservierungen
Content-Type: application/json

{

  "kundenId": 1,
  "tischIds": [1,2,3],
  "startZeit" : "2021-06-01T12:00:00",
  "endZeit" : "2021-06-01T13:00:00",
  "personen": 3
}

###
POST http://localhost:8080/tische
Content-Type: application/json

{
  "id": 20,

  "anzahlPlaetze": 4

}

###
GET http://localhost:8080/kunden/1
Content-Type: application/json

